version: '3.8'

services:
  fastapi-app:
    image: rslim087/fastapi-prometheus:latest  # Mantenha essa se for personalizada
    container_name: fastapi-app
    ports:
      - "8000:8000"
    networks:
      - monitoring
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.52.0  # Última versão estável até maio/2025
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:10.4.2  # Última versão estável até maio/2025
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - monitoring
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana  # Persistência opcional

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-storage:
